% RI_psdPlot(data_head_fft, ...
%           'Hands free - Condition: Head - Mean power of every person', ...
%           'Handsfree-Head');
% RI_psdPlot(data_hand_fft, ...
%           'Hands free - Condition: Hand - Mean power of every person', ...
%           'Handsfree-Hand');
% RI_psdPlot(data_head_fft_mean, ...
%           'Hands free - Condition: Head - Power over all persons', ...
%           'Handsfree-HeadMean');
% RI_psdPlot(data_hand_fft_mean, ...
%           'Hands free - Condition: Hand - Power over all persons', ...
%           'Handsfree-HandMean');
% 
% data_fft_mean = cell(1,2);
% data_fft_mean{1} = data_hand_fft_mean;
% data_fft_mean{2} = data_head_fft_mean;
% 
% RI_psdPlot(data_fft_mean, ...
%           'Hands free - Condition: Hand & Head - Power over all persons', ...
%           'Handsfree-Compare-HandHeadMean');

RI_psdPlot(data_head_fft, ...
          'Hands restraint - Condition: Head - Mean power of every person', ...
          'Handsrestr-Head');
RI_psdPlot(data_hand_fft, ...
          'Hands restraint - Condition: Hand - Mean power of every person', ...
          'Handsrestr-Hand');
RI_psdPlot(data_head_fft_mean, ...
          'Hands restraint - Condition: Head - Power over all persons', ...
          'Handsrestr-HeadMean');
RI_psdPlot(data_hand_fft_mean, ...
          'Hands restraint - Condition: Hand - Power over all persons', ...
          'Handsrestr-HandMean');

data_fft_mean = cell(1,2);
data_fft_mean{1} = data_hand_fft_mean;
data_fft_mean{2} = data_head_fft_mean;

RI_psdPlot(data_fft_mean, ...
          'Hands restraint - Condition: Hand & Head - Power over all persons', ...
          'Handsrestr-Compare-HandHeadMean');